image: node:lts
stages:
  - build
  - staging

build:
  cache:
    paths:
      - node_modules/
      - .yarn
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn build
    - export VERSION=$(node -pe "require('./package.json').version")-$CI_COMMIT_SHORT_SHA
    - echo $VERSION > build/version.txt
    - sed -i "s/%%APP_VERSION%%/$VERSION/" build/index.html
    - du -h build
  artifacts:
    paths:
      - build

staging:
  stage: staging
  image: netroby/alpine-rsync
  dependencies:
    - build
  script:
    - echo "Deploying to staging"
    - cp ${SSH_PRIVATE_KEY} id_rsa
    - chmod 600 id_rsa
    - rsync -hrvz --delete -e 'ssh -p 222 -i id_rsa -o "StrictHostKeyChecking no"' build/ staging-@${SERVER_IP}:/home/staging-pi-monitor/build
    - echo "Staging deployed"
  environment:
    name: staging
    url: https://pistream-staging.pupil-labs.com/
